development:
  bucket: aero-smc-dev
  access_key_id: AKIAIHZVAEQP5546ASRQ
  secret_access_key: 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
  s3_host_name: s3-ap-northeast-1.amazonaws.com
test:
  bucket: aero-smc-test
  access_key_id: AKIAIHZVAEQP5546ASRQ
  secret_access_key: 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
  s3_host_name: s3-ap-northeast-1.amazonaws.com
production:
  bucket: aero-smc
  access_key_id: AKIAIHZVAEQP5546ASRQ
  secret_access_key: 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
  s3_host_name: s3-ap-northeast-1.amazonaws.com
