development:
  bucket: aero-smc-dev
  access_key_id: AKIAJSXHDP4E5UWEVHUA
  secret_access_key: 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
  s3_host_name: s3-ap-northeast-1.amazonaws.com
test:
  bucket: aero-smc-test
  access_key_id: AKIAJSXHDP4E5UWEVHUA
  secret_access_key: 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
  s3_host_name: s3-ap-northeast-1.amazonaws.com
production:
  bucket: aero-smc
  access_key_id: AKIAJSXHDP4E5UWEVHUA
  secret_access_key: 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
  s3_host_name: s3-ap-northeast-1.amazonaws.com
