development:
  bucket: aero-smc-dev
  access_key_id: AKIAJXDS4NH6ZS4KOHEQ
  secret_access_key: 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
  s3_host_name: s3-ap-northeast-1.amazonaws.com
test:
  bucket: aero-smc-test
  access_key_id: AKIAJXDS4NH6ZS4KOHEQ
  secret_access_key: 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
  s3_host_name: s3-ap-northeast-1.amazonaws.com
production:
  bucket: aero-smc
  access_key_id: AKIAJXDS4NH6ZS4KOHEQ
  secret_access_key: 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
  s3_host_name: s3-ap-northeast-1.amazonaws.com
