development:
  bucket: aero-smc-dev
  access_key_id: AKIAJ2TLFJAS3ISY3ZOA
  secret_access_key: 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
  s3_host_name: s3-ap-northeast-1.amazonaws.com
test:
  bucket: aero-smc-test
  access_key_id: AKIAJ2TLFJAS3ISY3ZOA
  secret_access_key: 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
  s3_host_name: s3-ap-northeast-1.amazonaws.com
production:
  bucket: aero-smc
  access_key_id: AKIAJ2TLFJAS3ISY3ZOA
  secret_access_key: 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
  s3_host_name: s3-ap-northeast-1.amazonaws.com
